=== PavlinaCherkezova/ASP_MusicStore/XSD schema/MusicStore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Musicshop">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CDs" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CD" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CD_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="CD_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="CD_label_name" type="xs:string"/>
                                        <xs:element name="CD_release_date" type="xs:date"/>
                                        <xs:element name="CD_price" type="xs:float"/>
                                        <xs:element name="CD_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DVDs" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DVD" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DVD_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="DVD_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="DVD_label_name" type="xs:string"/>
                                        <xs:element name="DVD_release_date" type="xs:date"/>
                                        <xs:element name="DVD_price" type="xs:float"/>
                                        <xs:element name="DVD_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Vinyls" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Vinyl" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Vinyl_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Vinyl_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Vinyl_label_name" type="xs:string"/>
                                        <xs:element name="Vinyl_release_date" type="xs:date"/>
                                        <xs:element name="Vinyl_price" type="xs:float"/>
                                        <xs:element name="Vinyl_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DeluxeEditions" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DeluxeEdition" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Deluxe_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberAlbums" type="xs:int"
                                                  use="optional"/>
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Deluxe_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Deluxe_label_name" type="xs:string"/>
                                        <xs:element name="Deluxe_release_date" type="xs:date"/>
                                        <xs:element name="Deluxe_price" type="xs:float"/>
                                        <xs:element name="Deluxe_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="FanMerchandise" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="T-shirts" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="T-shirt" maxOccurs="unbounded"
                                            minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="T_shirt_artist_name">
                                                  <xs:complexType>
                                                  <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="color" type="xs:string"
                                                  use="optional"/>
                                                  <xs:attribute name="size" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                  </xs:simpleContent>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="T-shirt_price" type="xs:float"/>
                                                  <xs:element name="T-shirt_image" type="xs:string"
                                                  />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls6.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="10">Blame it on Baby</DVD_album_name>
            <DVD_artist_name autograph="true">DaBaby</DVD_artist_name>
            <DVD_label_name>Music Co.</DVD_label_name>
            <DVD_release_date>2020-02-04</DVD_release_date>
            <DVD_price>18</DVD_price>
            <DVD_image>baby.jpg</DVD_image>
        </DVD>
        <DVD>
            <DVD_album_name>Chromatica</DVD_album_name>
            <DVD_artist_name autograph="false">Lady Gaga</DVD_artist_name>
            <DVD_label_name>Sony</DVD_label_name>
            <DVD_release_date>2020-05-04</DVD_release_date>
            <DVD_price>80</DVD_price>
            <DVD_image>gaga.jpg</DVD_image>
        </DVD>
    </DVDs>
    <DeluxeEditions>
        <DeluxeEdition>
            <Deluxe_album_name numberAlbums="2" numberSongs="18">After Hours</Deluxe_album_name>
            <Deluxe_artist_name autograph="false">The Weeknd</Deluxe_artist_name>
            <Deluxe_label_name>Sun</Deluxe_label_name>
            <Deluxe_release_date>2020-05-04</Deluxe_release_date>
            <Deluxe_price>48</Deluxe_price>
            <Deluxe_image>kylie-minogue-kylie-christmas.jpg</Deluxe_image>
        </DeluxeEdition>
    </DeluxeEditions>
    <FanMerchandise>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls10.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <DVDs>
        <DVD>
            <DVD_album_name>This One's For You Too</DVD_album_name>
            <DVD_artist_name autograph="true">Luke Combs</DVD_artist_name>
            <DVD_label_name>Universal</DVD_label_name>
            <DVD_release_date>2019-05-04</DVD_release_date>
            <DVD_price>47</DVD_price>
            <DVD_image>luke.jpg</DVD_image>
        </DVD>
    </DVDs>
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name numberSongs="10">City On Lock</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">City Girls</Vinyl_artist_name>
            <Vinyl_label_name>Sony</Vinyl_label_name>
            <Vinyl_release_date>2016-05-04</Vinyl_release_date>
            <Vinyl_price>28</Vinyl_price>
            <Vinyl_image>lock.jpg</Vinyl_image>
        </Vinyl>
        <Vinyl>
            <Vinyl_album_name>Eternal Atake</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Lil Uzi Vert</Vinyl_artist_name>
            <Vinyl_label_name>Sony</Vinyl_label_name>
            <Vinyl_release_date>2018-05-04</Vinyl_release_date>
            <Vinyl_price>28</Vinyl_price>
            <Vinyl_image>atake.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <CDs>
        <CD>
            <CD_album_name>Astroworld</CD_album_name>
            <CD_artist_name autograph="true">Travis Scott</CD_artist_name>
            <CD_label_name>universal</CD_label_name>
            <CD_release_date>2020-05-04</CD_release_date>
            <CD_price>59</CD_price>
            <CD_image>travis.jpg</CD_image>
        </CD>
    </CDs>
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="30">Pray 4 Love</DVD_album_name>
            <DVD_artist_name autograph="false">Rod Wave</DVD_artist_name>
            <DVD_label_name>Universal</DVD_label_name>
            <DVD_release_date>2019-05-04</DVD_release_date>
            <DVD_price>49</DVD_price>
            <DVD_image>wave.jpg</DVD_image>
        </DVD>
    </DVDs>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="red" size="3">Sam Hunt</T_shirt_artist_name>
                <T-shirt_price>49</T-shirt_price>
                <T-shirt_image>hunt56.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <CDs>
        <CD>
            <CD_album_name>The Smartest</CD_album_name>
            <CD_artist_name autograph="true">Tee Grizzley</CD_artist_name>
            <CD_label_name>Sun</CD_label_name>
            <CD_release_date>2019-05-04</CD_release_date>
            <CD_price>26</CD_price>
            <CD_image>grizzley.jpg</CD_image>
        </CD>
    </CDs>
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="19">If I Know Me</DVD_album_name>
            <DVD_artist_name autograph="false">Morgan Wallen</DVD_artist_name>
            <DVD_label_name>Sony</DVD_label_name>
            <DVD_release_date>2018-05-04</DVD_release_date>
            <DVD_price>19</DVD_price>
            <DVD_image>morgan.jpg</DVD_image>
        </DVD>
    </DVDs>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="green">Megan Thee Stallion</T_shirt_artist_name>
                <T-shirt_price>56</T-shirt_price>
                <T-shirt_image>megan113.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls13.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name numberSongs="29">Scorpion</Vinyl_album_name>
            <Vinyl_artist_name autograph="true">Drake</Vinyl_artist_name>
            <Vinyl_label_name>Universal</Vinyl_label_name>
            <Vinyl_release_date>2020-05-04</Vinyl_release_date>
            <Vinyl_price>90</Vinyl_price>
            <Vinyl_image>drake23.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="red" size="3">Summer Walker</T_shirt_artist_name>
                <T-shirt_price>48</T-shirt_price>
                <T-shirt_image>walker2435.jpg</T-shirt_image>
            </T-shirt>
            <T-shirt>
                <T_shirt_artist_name color="blue" size="6">Post Malone</T_shirt_artist_name>
                <T-shirt_price>48</T-shirt_price>
                <T-shirt_image>malone243.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls7.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="20">Bigger Love</DVD_album_name>
            <DVD_artist_name autograph="true">John Legend</DVD_artist_name>
            <DVD_label_name>Sony</DVD_label_name>
            <DVD_release_date>2019-05-04</DVD_release_date>
            <DVD_price>19</DVD_price>
            <DVD_image>legend.jpg</DVD_image>
        </DVD>
    </DVDs>
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name>Homegrown</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Neil Young</Vinyl_artist_name>
            <Vinyl_label_name>Sony</Vinyl_label_name>
            <Vinyl_release_date>1998-05-04</Vinyl_release_date>
            <Vinyl_price>49</Vinyl_price>
            <Vinyl_image>young.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="gray" size="4">John legend</T_shirt_artist_name>
                <T-shirt_price>23</T-shirt_price>
                <T-shirt_image>legend12.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls12.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <CDs>
        <CD>
            <CD_album_name numberSongs="25">Eagles</CD_album_name>
            <CD_artist_name autograph="true">Eagles</CD_artist_name>
            <CD_label_name>Sun</CD_label_name>
            <CD_release_date>2019-05-04</CD_release_date>
            <CD_price>59.30</CD_price>
            <CD_image>eagles.jpg</CD_image>
        </CD>
    </CDs>
    <DeluxeEditions>
        <DeluxeEdition>
            <Deluxe_album_name numberAlbums="2">Hot Pink</Deluxe_album_name>
            <Deluxe_artist_name autograph="true">Doja Cat</Deluxe_artist_name>
            <Deluxe_label_name>Sony</Deluxe_label_name>
            <Deluxe_release_date>2019-05-04</Deluxe_release_date>
            <Deluxe_price>59</Deluxe_price>
            <Deluxe_image>doja.jpg</Deluxe_image>
        </DeluxeEdition>
        <DeluxeEdition>
            <Deluxe_album_name numberSongs="19">Changes</Deluxe_album_name>
            <Deluxe_artist_name autograph="true">Justin Bieber</Deluxe_artist_name>
            <Deluxe_label_name>Universal</Deluxe_label_name>
            <Deluxe_release_date>2019-05-04</Deluxe_release_date>
            <Deluxe_price>47</Deluxe_price>
            <Deluxe_image>bieber.jpg</Deluxe_image>
        </DeluxeEdition>
    </DeluxeEditions>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls14.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <DVDs>
        <DVD>
            <DVD_album_name>Just Cause Y'all Waited 2</DVD_album_name>
            <DVD_artist_name autograph="true">Lil Durk</DVD_artist_name>
            <DVD_label_name>Sony</DVD_label_name>
            <DVD_release_date>2019-05-04</DVD_release_date>
            <DVD_price>75</DVD_price>
            <DVD_image>durk.jpg</DVD_image>
        </DVD>
    </DVDs>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name size="6">Rod Wave</T_shirt_artist_name>
                <T-shirt_price>42</T-shirt_price>
                <T-shirt_image>wave274.jpg</T-shirt_image>
            </T-shirt>
            <T-shirt>
                <T_shirt_artist_name color="gray" size="7">Lil Mosey</T_shirt_artist_name>
                <T-shirt_price>59</T-shirt_price>
                <T-shirt_image>mosey848.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>
