=== PavlinaCherkezova/ASP_MusicStore/XSD schema/MusicStore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Musicshop">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CDs" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CD" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CD_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="CD_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="CD_label_name" type="xs:string"/>
                                        <xs:element name="CD_release_date" type="xs:date"/>
                                        <xs:element name="CD_price" type="xs:float"/>
                                        <xs:element name="CD_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DVDs" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DVD" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DVD_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="DVD_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="DVD_label_name" type="xs:string"/>
                                        <xs:element name="DVD_release_date" type="xs:date"/>
                                        <xs:element name="DVD_price" type="xs:float"/>
                                        <xs:element name="DVD_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Vinyls" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Vinyl" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Vinyl_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Vinyl_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Vinyl_label_name" type="xs:string"/>
                                        <xs:element name="Vinyl_release_date" type="xs:date"/>
                                        <xs:element name="Vinyl_price" type="xs:float"/>
                                        <xs:element name="Vinyl_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DeluxeEditions" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DeluxeEdition" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Deluxe_album_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="numberAlbums" type="xs:int"
                                                  use="optional"/>
                                                  <xs:attribute name="numberSongs" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Deluxe_artist_name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="autograph" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Deluxe_label_name" type="xs:string"/>
                                        <xs:element name="Deluxe_release_date" type="xs:date"/>
                                        <xs:element name="Deluxe_price" type="xs:float"/>
                                        <xs:element name="Deluxe_image" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="FanMerchandise" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="T-shirts" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="T-shirt" maxOccurs="unbounded"
                                            minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="T_shirt_artist_name">
                                                  <xs:complexType>
                                                  <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="color" type="xs:string"
                                                  use="optional"/>
                                                  <xs:attribute name="size" type="xs:int"
                                                  use="optional"/>
                                                  </xs:extension>
                                                  </xs:simpleContent>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="T-shirt_price" type="xs:float"/>
                                                  <xs:element name="T-shirt_image" type="xs:string"
                                                  />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls15.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="48">Lover</DVD_album_name>
            <DVD_artist_name autograph="false">Taylor Swift</DVD_artist_name>
            <DVD_label_name>Universal</DVD_label_name>
            <DVD_release_date>2016-05-04</DVD_release_date>
            <DVD_price>48</DVD_price>
            <DVD_image>taylor.jpg</DVD_image>
        </DVD>
        <DVD>
            <DVD_album_name numberSongs="29">Hamilton</DVD_album_name>
            <DVD_artist_name autograph="true">Various Artists</DVD_artist_name>
            <DVD_label_name>Sun</DVD_label_name>
            <DVD_release_date>2018-05-04</DVD_release_date>
            <DVD_price>59</DVD_price>
            <DVD_image>hamilton.jpg</DVD_image>
        </DVD>
    </DVDs>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="black">The Black Eyed Peas</T_shirt_artist_name>
                <T-shirt_price>48</T-shirt_price>
                <T-shirt_image>TBEP2324.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls4.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name numberSongs="8">GoodbyeGood Riddance</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Juice Wrld</Vinyl_artist_name>
            <Vinyl_label_name>Universal</Vinyl_label_name>
            <Vinyl_release_date>2005-05-04</Vinyl_release_date>
            <Vinyl_price>39</Vinyl_price>
            <Vinyl_image>riddance.jpg</Vinyl_image>
        </Vinyl>
        <Vinyl>
            <Vinyl_album_name>Goldmine</Vinyl_album_name>
            <Vinyl_artist_name autograph="true">Gabby Barrett</Vinyl_artist_name>
            <Vinyl_label_name>Sun</Vinyl_label_name>
            <Vinyl_release_date>2006-05-04</Vinyl_release_date>
            <Vinyl_price>59</Vinyl_price>
            <Vinyl_image>godmine.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
    <DeluxeEditions>
        <DeluxeEdition>
            <Deluxe_album_name numberAlbums="2" numberSongs="19">When We All Fall Asleep, Where Do We Go?</Deluxe_album_name>
            <Deluxe_artist_name autograph="false">Billie Eilish</Deluxe_artist_name>
            <Deluxe_label_name>Universal</Deluxe_label_name>
            <Deluxe_release_date>2019-05-04</Deluxe_release_date>
            <Deluxe_price>27.5</Deluxe_price>
            <Deluxe_image>billie.jpg</Deluxe_image>
        </DeluxeEdition>
    </DeluxeEditions>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name numberSongs="30">Chilombo</Vinyl_album_name>
            <Vinyl_artist_name autograph="true">Jhen√© Aiko</Vinyl_artist_name>
            <Vinyl_label_name>Sony</Vinyl_label_name>
            <Vinyl_release_date>2019-05-04</Vinyl_release_date>
            <Vinyl_price>59</Vinyl_price>
            <Vinyl_image>chilombo.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
    <DeluxeEditions>
        <DeluxeEdition>
            <Deluxe_album_name numberAlbums="1">Time Served</Deluxe_album_name>
            <Deluxe_artist_name autograph="true">Moneybagg Yo</Deluxe_artist_name>
            <Deluxe_label_name>Universal</Deluxe_label_name>
            <Deluxe_release_date>2019-05-04</Deluxe_release_date>
            <Deluxe_price>43</Deluxe_price>
            <Deluxe_image>yo.jpg</Deluxe_image>
        </DeluxeEdition>
    </DeluxeEditions>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name size="4">Juice Wrld</T_shirt_artist_name>
                <T-shirt_price>30</T-shirt_price>
                <T-shirt_image>wrld3423.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/XSD schema/MusicStore5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <CDs>
        <CD>
            <CD_album_name numberSongs="0">CD_album_name0</CD_album_name>
            <CD_artist_name autograph="false">CD_artist_name0</CD_artist_name>
            <CD_label_name>CD_label_name0</CD_label_name>
            <CD_release_date>2006-05-04</CD_release_date>
            <CD_price>0</CD_price>
            <CD_image>CD_image0</CD_image>
        </CD>
        <CD>
            <CD_album_name numberSongs="0">CD_album_name1</CD_album_name>
            <CD_artist_name autograph="false">CD_artist_name1</CD_artist_name>
            <CD_label_name>CD_label_name1</CD_label_name>
            <CD_release_date>2006-05-04</CD_release_date>
            <CD_price>0</CD_price>
            <CD_image>CD_image1</CD_image>
        </CD>
    </CDs>
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="0">DVD_album_name0</DVD_album_name>
            <DVD_artist_name autograph="false">DVD_artist_name0</DVD_artist_name>
            <DVD_label_name>DVD_label_name0</DVD_label_name>
            <DVD_release_date>2006-05-04</DVD_release_date>
            <DVD_price>0</DVD_price>
            <DVD_image>DVD_image0</DVD_image>
        </DVD>
        <DVD>
            <DVD_album_name numberSongs="0">DVD_album_name1</DVD_album_name>
            <DVD_artist_name autograph="false">DVD_artist_name1</DVD_artist_name>
            <DVD_label_name>DVD_label_name1</DVD_label_name>
            <DVD_release_date>2006-05-04</DVD_release_date>
            <DVD_price>0</DVD_price>
            <DVD_image>DVD_image1</DVD_image>
        </DVD>
    </DVDs>
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name numberSongs="0">Vinyl_album_name0</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Vinyl_artist_name0</Vinyl_artist_name>
            <Vinyl_label_name>Vinyl_label_name0</Vinyl_label_name>
            <Vinyl_release_date>2006-05-04</Vinyl_release_date>
            <Vinyl_price>0</Vinyl_price>
            <Vinyl_image>Vinyl_image0</Vinyl_image>
        </Vinyl>
        <Vinyl>
            <Vinyl_album_name numberSongs="0">Vinyl_album_name1</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Vinyl_artist_name1</Vinyl_artist_name>
            <Vinyl_label_name>Vinyl_label_name1</Vinyl_label_name>
            <Vinyl_release_date>2006-05-04</Vinyl_release_date>
            <Vinyl_price>0</Vinyl_price>
            <Vinyl_image>Vinyl_image1</Vinyl_image>
        </Vinyl>
    </Vinyls>
    <DeluxeEditions>
        <DeluxeEdition>
            <Deluxe_album_name numberAlbums="0" numberSongs="0">Deluxe_album_name0</Deluxe_album_name>
            <Deluxe_artist_name autograph="false">Deluxe_artist_name0</Deluxe_artist_name>
            <Deluxe_label_name>Deluxe_label_name0</Deluxe_label_name>
            <Deluxe_release_date>2006-05-04</Deluxe_release_date>
            <Deluxe_price>0</Deluxe_price>
            <Deluxe_image>Deluxe_image0</Deluxe_image>
        </DeluxeEdition>
        <DeluxeEdition>
            <Deluxe_album_name numberAlbums="0" numberSongs="0">Deluxe_album_name1</Deluxe_album_name>
            <Deluxe_artist_name autograph="false">Deluxe_artist_name1</Deluxe_artist_name>
            <Deluxe_label_name>Deluxe_label_name1</Deluxe_label_name>
            <Deluxe_release_date>2006-05-04</Deluxe_release_date>
            <Deluxe_price>0</Deluxe_price>
            <Deluxe_image>Deluxe_image1</Deluxe_image>
        </DeluxeEdition>
    </DeluxeEditions>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="color0" size="0">T_shirt_artist_name0</T_shirt_artist_name>
                <T-shirt_price>0</T-shirt_price>
                <T-shirt_image>T-shirt_image0</T-shirt_image>
            </T-shirt>
            <T-shirt>
                <T_shirt_artist_name color="color1" size="0">T_shirt_artist_name1</T_shirt_artist_name>
                <T-shirt_price>0</T-shirt_price>
                <T-shirt_image>T-shirt_image1</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls9.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <CDs>
        <CD>
            <CD_album_name numberSongs="19">YHLQMDLG</CD_album_name>
            <CD_artist_name autograph="false">Bad Bunny</CD_artist_name>
            <CD_label_name>Sony</CD_label_name>
            <CD_release_date>2020-05-04</CD_release_date>
            <CD_price>30</CD_price>
            <CD_image>bunny.jpg</CD_image>
        </CD>
    </CDs>
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name>Please Excuse Me For Being Antisocial</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Roddy Ricch</Vinyl_artist_name>
            <Vinyl_label_name>Universal</Vinyl_label_name>
            <Vinyl_release_date>2018-05-04</Vinyl_release_date>
            <Vinyl_price>18</Vinyl_price>
            <Vinyl_image>rody.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
    <DeluxeEditions>
        <DeluxeEdition>
            <Deluxe_album_name numberSongs="18">What You See Is What You Get</Deluxe_album_name>
            <Deluxe_artist_name autograph="false">Luke Combs</Deluxe_artist_name>
            <Deluxe_label_name>Sun</Deluxe_label_name>
            <Deluxe_release_date>2019-05-04</Deluxe_release_date>
            <Deluxe_price>17</Deluxe_price>
            <Deluxe_image>luke.jpg</Deluxe_image>
        </DeluxeEdition>
    </DeluxeEditions>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls11.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="19">BeerbongsBentleys</DVD_album_name>
            <DVD_artist_name autograph="true">Post Malone</DVD_artist_name>
            <DVD_label_name>Sun</DVD_label_name>
            <DVD_release_date>2018-05-04</DVD_release_date>
            <DVD_price>48</DVD_price>
            <DVD_image>malone.jpg</DVD_image>
        </DVD>
    </DVDs>
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name>Future Nostalgia</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Dua Lipa</Vinyl_artist_name>
            <Vinyl_label_name>Universal</Vinyl_label_name>
            <Vinyl_release_date>2020-05-04</Vinyl_release_date>
            <Vinyl_price>48</Vinyl_price>
            <Vinyl_image>lipa.jpg</Vinyl_image>
        </Vinyl>
        <Vinyl>
            <Vinyl_album_name numberSongs="18">Meet The Woo 2</Vinyl_album_name>
            <Vinyl_artist_name autograph="true">Pop Smoke</Vinyl_artist_name>
            <Vinyl_label_name>Sun</Vinyl_label_name>
            <Vinyl_release_date>2019-05-04</Vinyl_release_date>
            <Vinyl_price>49</Vinyl_price>
            <Vinyl_image>woo.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMls1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <CDs>
        <CD>
            <CD_album_name numberSongs="15">Rough and Rowdy Ways</CD_album_name>
            <CD_artist_name autograph="false">Bob Dylan</CD_artist_name>
            <CD_label_name>Sony</CD_label_name>
            <CD_release_date>2018-05-05</CD_release_date>
            <CD_price>23</CD_price>
            <CD_image>dylan.jpg</CD_image>
        </CD>
    </CDs>
    <Vinyls>
        <Vinyl>
            <Vinyl_album_name>Dark Lane Demo Tapes</Vinyl_album_name>
            <Vinyl_artist_name autograph="false">Drake</Vinyl_artist_name>
            <Vinyl_label_name>Sony</Vinyl_label_name>
            <Vinyl_release_date>2020-10-04</Vinyl_release_date>
            <Vinyl_price>50</Vinyl_price>
            <Vinyl_image>drake.jpg</Vinyl_image>
        </Vinyl>
    </Vinyls>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="blue">The Weeknd</T_shirt_artist_name>
                <T-shirt_price>20</T-shirt_price>
                <T-shirt_image>nirvana-live-at-paramount.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>

=== PavlinaCherkezova/ASP_MusicStore/loadXMLs/GeneratedXMLs16.xml
<?xml version="1.0" encoding="UTF-8"?>
<Musicshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/polic/Desktop/uni/asp/MusicStore/XSD%20schema/MusicStore.xsd">
    <CDs>
        <CD>
            <CD_album_name>Artist 2.0</CD_album_name>
            <CD_artist_name autograph="false">A Boogie wit da Hoodie</CD_artist_name>
            <CD_label_name>Sony</CD_label_name>
            <CD_release_date>2006-05-04</CD_release_date>
            <CD_price>0</CD_price>
            <CD_image>boogie.jpg</CD_image>
        </CD>
    </CDs>
    <DVDs>
        <DVD>
            <DVD_album_name numberSongs="9">Lamb Of God</DVD_album_name>
            <DVD_artist_name autograph="true">Lamb Of God</DVD_artist_name>
            <DVD_label_name>Universal</DVD_label_name>
            <DVD_release_date>2019-05-04</DVD_release_date>
            <DVD_price>16.5</DVD_price>
            <DVD_image>lamb.jpg</DVD_image>
        </DVD>
    </DVDs>
    <Vinyls>
    </Vinyls>
    <DeluxeEditions>
        <DeluxeEdition>
            <Deluxe_album_name numberAlbums="2">High Off Life</Deluxe_album_name>
            <Deluxe_artist_name autograph="false">Future</Deluxe_artist_name>
            <Deluxe_label_name>Universal</Deluxe_label_name>
            <Deluxe_release_date>2019-05-04</Deluxe_release_date>
            <Deluxe_price>67</Deluxe_price>
            <Deluxe_image>kylie-christmas.jpg</Deluxe_image>
        </DeluxeEdition>
    </DeluxeEditions>
    <FanMerchandise>
        <T-shirts>
            <T-shirt>
                <T_shirt_artist_name color="color1" size="4">Future</T_shirt_artist_name>
                <T-shirt_price>15</T-shirt_price>
                <T-shirt_image>bring-me-the-horizon.jpg</T-shirt_image>
            </T-shirt>
        </T-shirts>
    </FanMerchandise>
</Musicshop>
